version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filament-blog-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: filament-blog-web
    restart: unless-stopped
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf # Use the modified nginx.conf
    environment:
      PORT: 8080 # Nginx will use this port
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: filament-blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
